disabled_rules:
  - vertical_parameter_alignment
  - mark
  - cyclomatic_complexity
  - implicit_getter
  - function_body_length
  - type_body_length
  - function_parameter_count
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

line_length: 150

file_length:
  warning: 600

identifier_name:
  min_length: 2
  
type_name:
  max_length: 50

excluded:
  - Pods
  - Carthage
  - Package.swift
